//! JavaScript try...catch...finally Statement

// ? The try, catch and finally blocks are used to handle exceptions (a type of an error).

//? Types of Errors

//? Syntax Error: Error in the syntax. For example, if you write consol.log('your result');, the above program throws a syntax error. The spelling of console is a mistake in the above code.

//? Runtime Error: This type of error occurs during the execution of the program. For example,
//? calling an invalid function or a variable.

//? JavaScript try...catch Statement

{
    // //? The try...catch statement is used to handle the exceptions. 
    // try {
    //     //? body of try
    // } 
    // catch(error) {
    //     //? body of catch  
    // }

    // //? The main code is inside the try block. While executing the try block, if any error occurs, it goes to the catch block. The catch block handles the errors as per the catch statements.
}



//! JavaScript try...catch...finally Statement

// You can also use the try...catch...finally statement to handle exceptions. The finally block executes both when the code runs successfully or if an error occurs.

{
    // try {
    //     //? try_statements
    // } 
    // catch(error) {
    //     //? catch_statements  
    // }
    // finally() {
    //     //? codes that gets executed anyway
    // }
}





//!--------------------------------------------------------//



// let a = 10 ;

// try{

//     a == 50

//     console.log('arr is low')


// }catch(err)
// {
//     console.log('arr isc low')


// }

{
// ? throw

// let a = 1;

// if(a==10)
// {
//     console.log('value is same');
// }else{
//     throw SyntaxError('err is a program')
// }

}

//?  try ann catch 

// try{

//     // let a = 12;
//     console.log(a)
// }catch(err)
// {
//     console.log("err" + err);
// }



